CoreBundle\Entity\SingleRating:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\SingleRatingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        discussion:
            type: string
            length: 2
        presentation:
            type: string
            length: 2
        totalIhk:
            type: string
            length: 2
            column: total_ihk
        totalGso:
            type: string
            length: 2
            column: total_gso
    oneToOne:
        student:
            targetEntity: Student
            inversedBy: singleRating
            joinColumn:
                name: student_id
                referencedColumnName: id
                onDelete: CASCADE