CoreBundle\Entity\Topic:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\TopicRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        projectGroup:
            targetEntity: ProjectGroup
            mappedBy: topic
