<?php

namespace CoreBundle\Repository;

/**
 * GroupRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
