<?php

namespace CoreBundle\Repository;

/**
 * ProjectClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectClassRepository extends \Doctrine\ORM\EntityRepository
{
}
