<?php

namespace CoreBundle\Repository;

/**
 * ProjectGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
