<?php

namespace CoreBundle\Repository;

/**
 * SingleRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SingleRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
