<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function getSearchResult($searchTerms = null, $advisor = null, $topic = null)
    {
        $query = $this->getEntityManager()->createQueryBuilder('s')
            ->select('s')
            ->from('CoreBundle:Student', 's')
            ->innerJoin('s.projectGroup', 'g');

            if ($advisor != null) {
                $query->andWhere('g.advisor = :advisor')
                    ->setParameter('advisor', $advisor);
            }

            if ($topic != null) {
                $query->andWhere('g.topic = :topic')
                    ->setParameter('topic', $topic);
            }


            foreach ($searchTerms as $searchTerm) {
                if ($searchTerm) {
                    $query->andWhere('s.name LIKE :term')
                        ->setParameter('term', '%' . $searchTerm . '%');
                }
            }


        //var_dump($query->getDQL());die();

        $res = $query->getQuery();


        /**
        if ($advisor != '') {
        $qb->where('s.advisor = :advisor')
        ->setParameter('advisor', $advisor);
        }
        if ($topic != '') {
        $qb->andWhere('s.topic = :topic')
        ->setParameter('topic', $topic);
        }
        foreach ($searchTerms as $searchTerm) {
        $qb->andWhere('s.name LIKE :term')
        ->setParameter('term', $searchTerm);
        }
         **/

        return $res->getResult();
    }
}
